name = "UnitfulOfu"
uuid = "c38b2286-e06d-5aaf-ac8c-46cde5afb720"
license = "MIT"
desc = "Oil Field Units extension to Unitful"
authors = ["Rob J Goedman <goedman@icloud.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Unitful = "^0"
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
